# Generated by Django 3.2.3 on 2021-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=1000)),
                ('level', models.CharField(choices=[('Application', 'Application'), ('Evaluation', 'Evaluation'), ('Synthesis', 'Synthesis'), ('Knowledge', 'Knowledge'), ('Comprehenssion', 'Comprehenssion'), ('Analysis', 'Analysis')], max_length=100)),
                ('module', models.CharField(max_length=1000)),
                ('mark', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
