# Generated by Django 3.2.3 on 2021-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Application', 'Application'), ('Evaluation', 'Evaluation'), ('Synthesis', 'Synthesis'), ('Knowledge', 'Knowledge'), ('Comprehension', 'Comprehenssion'), ('Analysis', 'Analysis')], max_length=100),
        ),
    ]
